# Generated by Django 2.2.9 on 2020-09-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrasesmodel',
            old_name='image',
            new_name='imagem',
        ),
    ]
